import { Fragment } from "react";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container grid grid-cols-12 mx-auto">
        <div className="h-48 shadow-md card bg-base-100 col-span-full md:col-span-4">
          <div className="card-body">
            <h2 className="card-title">Gateway status</h2>
            <span className="my-4 text-4xl font-bold text-center text-success">
              ONLINE
            </span>
          </div>
        </div>
      </main>
    </Fragment>
  );
};

export default Home;
