import { Fragment } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { useQuery } from "@tanstack/react-query";
import { getStatus } from "../utils/api";
import Spinner from "../components/Spinner";
import ErrorAlert from "../components/ErrorAlert";

const Home: NextPage = () => {
  const {
    data: status,
    isLoading,
    isError,
    refetch,
  } = useQuery(["status"], getStatus);

  if (isLoading) return <Spinner />;
  if (isError) return <ErrorAlert callBack={refetch} />;
  return (
    <Fragment>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container grid grid-cols-12 mx-auto">
        <div className="h-48 shadow-md card bg-base-100 col-span-full md:col-span-4">
          <div className="card-body">
            <h2 className="card-title">Gateway status</h2>
            <span className="my-4 text-4xl font-bold text-center text-success">
              {status ?? "N/A"}
            </span>
          </div>
        </div>
      </main>
    </Fragment>
  );
};

export default Home;
